import { For, Show } from "solid-js";

const short = (value = "") => value.length > 18 ? `${value.slice(0, 9)}…${value.slice(-7)}` : value;

export function SettingsPage(props) {
  return <section class="overflow-hidden rounded border border-emerald-900 bg-emerald-950/10">
    <div class="border-b border-emerald-900 p-5"><h1 class="font-mono text-lg text-lime-200">SETTINGS</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-emerald-600">Global blocks apply to relay collection, search, Relay Explorer, graphs, saved research when reopened, and the local archive. Events from blocked authors are discarded before storage and analysis.</p></div>
    <div class="border-b border-emerald-900 p-5"><div class="font-mono text-[10px] tracking-[.14em] text-cyan-300">SEED ACCOUNTS · {props.seeds.length}</div><p class="mt-2 text-xs leading-5 text-emerald-700">A private starting list for research. Search recent activity from all seeds, or use up to eight of them to direct the next Relay Explorer scan. Nothing is published to Nostr.</p><form onSubmit={(event) => { event.preventDefault(); props.onAddSeed(); }} class="mt-3 flex gap-2"><input value={props.seedInput} onInput={(event) => props.setSeedInput(event.currentTarget.value)} placeholder="npub, nprofile, or 64-character public key" class="min-w-0 flex-1 rounded border border-emerald-900 bg-black/20 px-3 py-2 font-mono text-xs text-emerald-200 outline-none focus:border-cyan-700"/><button class="rounded border border-cyan-900 px-4 py-2 font-mono text-xs text-cyan-300 hover:bg-cyan-950">add seed</button></form><Show when={props.seeds.length}><div class="mt-3 flex flex-wrap gap-2"><button onClick={props.onSearchSeeds} class="rounded border border-lime-800 px-3 py-2 font-mono text-[10px] text-lime-300 hover:bg-lime-300 hover:text-black">search all seeds</button><button onClick={props.onDirectSeeds} class="rounded border border-cyan-900 px-3 py-2 font-mono text-[10px] text-cyan-300 hover:bg-cyan-950">use in Relay Explorer</button></div></Show><div class="mt-5"><Show when={props.seeds.length} fallback={<div class="rounded border border-emerald-950 p-6 text-center text-sm text-emerald-800">No seed accounts yet.</div>}><For each={props.seeds}>{(account) => <div class="flex flex-wrap items-center gap-2 border-b border-emerald-950 py-3"><div class="min-w-48 flex-1"><div class="truncate text-sm text-cyan-200">{account.name || short(account.pubkey)}</div><div class="mt-1 truncate font-mono text-[10px] text-emerald-800">{account.pubkey}</div></div><button onClick={() => props.onOpenSeed(account.pubkey)} class="rounded border border-emerald-900 px-2 py-1.5 font-mono text-[10px] text-emerald-500 hover:text-cyan-300">open</button><button onClick={() => props.onSearchSeed(account.pubkey)} class="rounded border border-emerald-900 px-2 py-1.5 font-mono text-[10px] text-emerald-500 hover:text-lime-300">new search</button><button onClick={() => props.onDirectSeed(account.pubkey)} class="rounded border border-cyan-950 px-2 py-1.5 font-mono text-[10px] text-cyan-600 hover:text-cyan-300">direct scan</button><button onClick={() => props.onRemoveSeed(account.pubkey)} class="rounded border border-amber-950 px-2 py-1.5 font-mono text-[10px] text-amber-700 hover:text-amber-400">remove</button></div>}</For></Show></div></div>
    <div class="p-5"><div class="font-mono text-[10px] tracking-[.14em] text-lime-300">GLOBAL ACCOUNT BLOCK LIST · {props.accounts.length}</div><form onSubmit={(event) => { event.preventDefault(); props.onAdd(); }} class="mt-3 flex gap-2"><input value={props.draft} onInput={(event) => props.setDraft(event.currentTarget.value)} placeholder="npub, nprofile, or 64-character public key" class="min-w-0 flex-1 rounded border border-emerald-900 bg-black/20 px-3 py-2 font-mono text-xs text-emerald-200 outline-none focus:border-lime-700"/><button class="rounded border border-lime-800 px-4 py-2 font-mono text-xs text-lime-300 hover:bg-lime-300 hover:text-black">block account</button></form><p class="mt-2 text-[10px] text-emerald-800">Blocking removes the author’s existing events from local storage. Other people’s notes that merely mention the account remain visible.</p><div class="mt-5"><Show when={props.accounts.length} fallback={<div class="rounded border border-emerald-950 p-6 text-center text-sm text-emerald-800">No globally blocked accounts.</div>}><For each={props.accounts}>{(account) => <div class="flex items-center gap-3 border-b border-emerald-950 py-3"><div class="min-w-0 flex-1"><div class="truncate text-sm text-emerald-300">{account.name || short(account.pubkey)}</div><div class="mt-1 truncate font-mono text-[10px] text-emerald-800">{account.pubkey}</div></div><button onClick={() => props.onUnblock(account.pubkey)} class="rounded border border-amber-900 px-3 py-1.5 font-mono text-[10px] text-amber-500 hover:border-amber-600">unblock</button></div>}</For></Show></div></div>
    <div class="border-t border-emerald-900 p-5"><div class="font-mono text-[10px] tracking-[.14em] text-lime-300">BLOCKED NAME STRINGS · {props.names.length}</div><p class="mt-2 text-xs leading-5 text-emerald-700">Case-insensitive contains matching. If either the account name or display name contains the text, that account’s events are excluded globally.</p><form onSubmit={(event) => { event.preventDefault(); props.onAddName(); }} class="mt-3 flex gap-2"><input value={props.nameDraft} onInput={(event) => props.setNameDraft(event.currentTarget.value)} placeholder="text contained in unwanted names" class="min-w-0 flex-1 rounded border border-emerald-900 bg-black/20 px-3 py-2 font-mono text-xs text-emerald-200 outline-none focus:border-lime-700"/><button class="rounded border border-lime-800 px-4 py-2 font-mono text-xs text-lime-300 hover:bg-lime-300 hover:text-black">block names containing</button></form><div class="mt-4 flex flex-wrap gap-2"><For each={props.names}>{(pattern) => <div class="flex items-center gap-2 rounded border border-red-950 bg-red-950/10 px-3 py-2"><span class="font-mono text-xs text-red-400">contains “{pattern}”</span><button aria-label={`Remove ${pattern} name rule`} onClick={() => props.onRemoveName(pattern)} class="text-red-800 hover:text-red-400">×</button></div>}</For></div></div>
    <div class="border-t border-emerald-900 p-5"><div class="font-mono text-[10px] tracking-[.14em] text-cyan-300">PORTABLE MODERATION · NIP-51</div><p class="mt-2 text-xs leading-5 text-emerald-700">These private local rules hide matching topics, words, event threads, and relay-sourced events. Import accepts a public kind 10000 event; export creates an unsigned draft and never publishes anything.</p><div class="mt-4 grid gap-3 sm:grid-cols-2"><MuteRuleField label="TOPICS" value={props.muteRules.topics} placeholder="spam, nsfw" onChange={(topics) => props.onMuteRules({ ...props.muteRules, topics })}/><MuteRuleField label="WORDS / PHRASES" value={props.muteRules.words} placeholder="giveaway, unwanted phrase" onChange={(words) => props.onMuteRules({ ...props.muteRules, words })}/><MuteRuleField label="EVENT / THREAD IDS" value={props.muteRules.events} placeholder="64-character IDs" onChange={(events) => props.onMuteRules({ ...props.muteRules, events })}/><MuteRuleField label="RELAYS" value={props.muteRules.relays} placeholder="wss://relay.example" onChange={(relays) => props.onMuteRules({ ...props.muteRules, relays })}/></div><textarea value={props.muteImport} onInput={(event) => props.setMuteImport(event.currentTarget.value)} placeholder="Paste a public kind 10000 mute-list event as JSON" class="mt-4 h-28 w-full resize-y rounded border border-emerald-900 bg-black/20 p-3 font-mono text-[10px] text-emerald-300 outline-none"/><div class="mt-2 flex gap-2"><button onClick={props.onImportMute} class="rounded border border-cyan-900 px-3 py-2 font-mono text-[10px] text-cyan-300">import event</button><button onClick={props.onExportMute} class="rounded border border-emerald-900 px-3 py-2 font-mono text-[10px] text-emerald-400">export unsigned draft</button></div></div>
  </section>;
}

function MuteRuleField(props) {
  return <label class="font-mono text-[9px] text-emerald-700">{props.label}<textarea value={props.value.join("\n")} onChange={(event) => props.onChange(event.currentTarget.value.split(/[\n,]+/).map((value) => value.trim()).filter(Boolean))} placeholder={props.placeholder} class="mt-1 h-20 w-full resize-y rounded border border-emerald-900 bg-black/20 p-2 text-[10px] text-emerald-300 outline-none"/></label>;
}
